language: java
jdk:
  - oraclejdk8
sudo: required
services:
  - docker
before_install:
  - maze/build-sidekick.sh
script:
  - mvn clean install -P docker-build -Ddocker.registry=''
cache:
  directories:
  - $HOME/.m2
after_success:
  - bash <(curl -s https://codecov.io/bash)
