language: java
jdk:
  - oraclejdk8
sudo: required
services:
  - docker
script:
  - mvn test
  - maze/build-sidekick.sh
  - mvn package -P build-docker -Ddocker.registry='' -pl :admin-gui
  - docker pull nsqio/nsq:v0.3.7
  - docker pull verb/socat
  - docker pull gliderlabs/consul-server
  - docker pull nginx
  - mvn scalatest:test -pl maze
cache:
  directories:
  - $HOME/.m2
after_success:
  - bash <(curl -s https://codecov.io/bash)
