language: java
jdk:
  - oraclejdk8
sudo: required
services:
  - docker
script:
  - maze/build-sidekick.sh
  - mvn package -P build-docker -Ddocker.registry='' -pl :admin-gui
  - mvn test
cache:
  directories:
  - $HOME/.m2
after_success:
  - bash <(curl -s https://codecov.io/bash)
