language: java
jdk:
  - oraclejdk8
sudo: required
services:
  - docker
before_install:
  - curl -sL https://github.com/jpm4j/jpm4j.installers/raw/master/dist/biz.aQute.jpm.run.jar >jpm4j.jar
  - java -jar jpm4j.jar -u init
  - ~/jpm/bin/jpm install com.codacy:codacy-coverage-reporter:assembly
  - export VERSION=`mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate  -Dexpression=project.version | grep -v "\[" `  
script:
  - mvn package
  - docker info
  - docker build -t strowgr/admin:$VERSION -t strowgr/admin:latest admin
  - docker pull strowgr/sidekick:0.2.6
  - docker pull java:8
  - docker pull nsqio/nsq:v0.3.7
  - docker pull verb/socat
  - docker pull gliderlabs/consul-server
  - docker pull nginx
  - mvn scalatest:test -pl maze
cache:
  directories:
    - $HOME/.m2
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ~/jpm/bin/codacy-coverage-reporter -l Java -r admin/admin-gui/target/site/jacoco/jacoco.xml
  - ls -l ${TRAVIS_BUILD_DIR}/admin/admin-gui/target/  
deploy:
  - provider: releases
    api_key:
      secure: VbcfSpaI8QBfQ22+EjQ/UCA1uUs9JzDlw2ImH28MtnkuY1JV1FMPVjzEZoTFc4elnOMgKqfdhPSdagNh9758b1chqUEAEF24yYQnpt5BVWYLKLeOC4lEy2wXeLW1Qxuy0NE+aP0oIxP5i/RnyVYF91i/K2W4MmYBkngfTC401++sTB+KsUnhg5wGZ/dw7I9Qh72bC+tg7gI0mH16U2uckQS10Hm+yPauTOfb1X/tvkNCRC8RH4yWZGr6RVVQUc/nAp8SYMG4Q0S1VYlRpLXco9Fd7uWvWKk7XiJgvf3R4nOjF40oz+jmYjaZ4gBhkZzHx8NvNwa7PpfRL2/xUisf2MRckuBErxIN6uYifKEunS+Kt9BFsaHpwL8htE129coHNoFZX99f8Td0GQV4wlwR0kAPbhY1jYkXDyDdcjN6qs1zTSgvIIRXLCGu/zMAwNklxZ/MyyK4fagA4ynvTCtJmDvNpxIQiitOAwxyn6EYjQwow9/EeElIyw7j+N5LF6XjxlRKK1emAGdzvuTqi8UT6Swz26Q3h3lzefyxtP15RkmJgrYGDBBNS+W7p6RCfeS1apLB02FJ9SrVgh43Ol0fttxQlDw+VcPS+cc8Z1vXGHOKzQOuuLa/+Fxiq8E8BYIupedou060PT2IIs352wh5M2d9LjX1fS0MgdTwsSYqPCo=
    file: ${TRAVIS_BUILD_DIR}/admin/admin-gui/target/admin-gui-${VERSION}.jar
    skip_cleanup: true
    on:
      tags: true
      repo: voyages-sncf-technologies/strowgr
      branch: master
  - provider: script
    skip_cleanup: true
    script: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push strowgr/admin:$VERSION && docker push strowgr/admin:latest
    on:
      tags: true