version: '2'

services:

  # Single instance of consul
  consul:
    image: gliderlabs/consul-server
    container_name: consul
    command: -bootstrap
    ports:
      - 8500:8500

  # Single instance of nsqlookupd
  nsqlookupd:
    image: nsqio/nsq
    container_name: nsqlookupd
    command: /nsqlookupd -http-address=nsqlookupd:4161 -tcp-address=nsqlookupd:4160
    ports:
      - "4160:4160"
      - "4161:4161"

  # Only one producer
  nsqd:
    image: nsqio/nsq
    container_name: nsqd
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 --broadcast-address=nsqd
    ports:
      - "4150:4150"
      - "4151:4151"
    depends_on:
      - nsqlookupd

  #  HA proxies
  ha-master:
    image: haaas/haaasd:1.0.0
    container_name: haaasd-master
    volumes:
      - ./data/master/haaasd.conf:/haaasd.conf
      - ./data/master/hapadm:/HOME/hapadm
    ports:
      - 52000:52000
      - 50000
      - 50080:50080
    extra_hosts:
      - "larimar:1.2.3.4"

  ha-slave:
    image: haaas/haaasd:1.0.0
    container_name: haaasd-slave
    volumes:
      - ./data/slave/haaasd.conf:/haaasd.conf
      - ./data/slave/hapadm:/HOME/hapadm
    ports:
      - 50000
      - 52001:52000
    extra_hosts:
      - "larimar:1.2.3.4"

  # NSQ admin
  nsq-admin:
    container_name: nsqadmin
    image: nsqio/nsq
    ports:
      - "4171:4171"
    command: /nsqadmin -http-address="0.0.0.0:4171" --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
      - nsqd

  # Webapp instances
  webapp-1:
    image: haaas/webapp:1.0.0
    ports:
     - 50180:50080
    command: instance1

  webapp-2:
    image: haaas/webapp:1.0.0
    ports:
     - 50080
    command: instance2

  webpage:
    image: nginx
    ports:
     - 80:80
    volumes:
     - ./static/:/usr/share/nginx/html
     - ./static/nginx.conf:/etc/nginx/nginx.conf

  gitlab:
    image: gitlab/gitlab-ce
    ports:
      - 50280:80
    volumes:
      - /etc/gitlab
      - /var/log/gitlab
      - /var/opt/gitlab
    environment:
      - GITLAB_ROOT_PASSWORD=password

networks:
  default:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 192.168.10.0/24
         gateway: 192.168.10.254
